### ISSUE TITLE
errors when using long NUMBERS in table

### ISSUE THREAD

**Issue by rahulbats** [CraZySacX/node-jdbc#100]
if the table has a big number column like NUMBER(13,0) we are seeing wrong data as it is mapped to a float or double instead of long.

**Comment by rahulbats** [comment]
i found out the problem. The problem is java float cannot hold very long numbers.
i changed the line in resultset.js 
from 
typeNames[java.getStaticFieldValue("java.sql.Types", "NUMERIC")]  = "Float";
to
typeNames[java.getStaticFieldValue("java.sql.Types", "NUMERIC")]  = "String";

Will this change be applied in your next release or is there a better way to handle this?

thanks

**Comment by CraZySacX** [comment]
This has been updated to use the recommended type mappings now (DECIMAL and NUMERIC are mapped to java.math.BigDecimal).   Let me know if you need an example of how to create a BigDecimal for use in statements.   Closing.

**Comment by romandoma** [comment]
Hi, can you share with us an example of how to use BigDecimal?
Now in a console.log the results is like:
`decnumber: nodeJava_java_math_BigDecimal {} `

Thanks!

**Comment by ed-watts-87** [comment]
Hi @romandoma did you ever find out how to handle BigDecimal?

@CraZySacX any tips?

Thanks

**Comment by CraZySacX** [comment]
When you get back a node-java wrapped object (nodeJava_java_math_BigDecimal), you have access to all of the functions exposed by the Java API in both a sync and async form.

For example, the [Java 7 BigDecimal API](http://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html) has a function called `intValue`.   To use this with the object you would get back in the resultset, you would do:

```
// Asynchronous Version
decnumber.intValue(function(err, intVal) {
  // Do stuff with intVal
})

// Synchronous Version
var intVal = decnumber.intValueSync();
// Do stuff with intVal
```

Take a look at [node-java](https://github.com/joeferner/node-java) for some more thorough examples of using node-java wrapped objects.

**Comment by CraZySacX** [comment]
I should also point out that you can create java objects for use in prepared statements as well.  I've included a snippet below, or you can take a look at the hsqldb tests for more complete examples.

```
var sqlTimestamp = myjava.newInstanceSync("java.sql.Timestamp", myjava.newLong(testDate));
statement.setTimestamp(1, sqlTimestamp, null, function(err) {
  if (err) {
    console.log(err);
  }
```

**Comment by ed-watts-87** [comment]
Thanks, works perfectly 👍
