### ISSUE TITLE
Redshift jar unable to connect

### ISSUE THREAD

**Issue by randeepbhatia** [CraZySacX/node-jdbc#103]
I tried using redshift jar as JDBC but it says cannot find the class.

**Comment by CraZySacX** [comment]
Did you specify the driver classname in the properties?   Older drivers do not support auto-loading of the driver, so you have to specify the class name so the driver can be loaded appropriately with Class.forName.

**Comment by CraZySacX** [comment]
Closing.  If this is still occurring, feel free to re-open.
