### ISSUE TITLE
JDBC backward comparability for older version jdbc@0.0.13

### ISSUE THREAD

**Issue by amiya-pattnaik** [CraZySacX/node-jdbc#104]
Hi Jozias,

Hope you will be in best of mind and health.
This is Amiya, I need your help on the  "node.JS JDBC module backward comparability for older version jdbc@0.0.13'
In our automation framework we are using your older older version of jdbc@0.0.13 to execute queries etc. It work fines on the older version of NODE JS, like 0.12.40 etc. But withe the latest version of the NodeJS, if we install the jdbc latest version, our existing automation code does not work - it says 'url undefined' etc.

and in the other way latest nodeJS does not support the jdbc@0.0.13' version.
We also installed the latest version of JDBC module but it does not work, as it does not support the code based on the  jdbc@0.0.13' version.
We can see that jdbc@0.0.13' and the latest version of jdbc are different. and the latest version does not have the backward comparability of the previous API's. Could you please advise us how to proceed?

We appreciate your help on this.

Thanks,
Amiya

**Comment by CraZySacX** [comment]
Closing this due to age. Feel free to re-open if you are still having issues.
