### ISSUE TITLE
Connection pool is reseting from a day to another

### ISSUE THREAD

**Issue by NetoriaN** [CraZySacX/node-jdbc#105]
We are using Intersystems Cachè database and our problem is that connection pool are killed from a day to another and creating the need to restart node docker server. is there a way to restart the connection if its down?

**Comment by CraZySacX** [comment]
For now, try using the ```purge``` method in Pool, then setting your pool to null, and then re-initializing the pool.

As this is coming up more often, I'm going to place some sanity checks in the pool to remove disconnected connections, and attempt to re-connect automatically.

**Comment by NetoriaN** [comment]
Great! Thank's a lot!

**Comment by diquevasc** [comment]
What does the purge method do?

**Comment by CraZySacX** [comment]
Call connection.close() on all the pool connections and resets the connection arrays to empty arrays.

**Comment by diquevasc** [comment]
Can I use the purge even if I declare like this: 

`var cacheDB = new JDBC(env.config);`

The call should be something like this:

`cacheDB.purge(function(err){...});`

Will it work?
