### ISSUE TITLE
Not able to get the result set for the SQL query being executed

### ISSUE THREAD

**Issue by amiya-pattnaik** [CraZySacX/node-jdbc#106]
Hi,
I am using the latest JDBC. below code is the sample code I am using in my test function to connect and execute it on Oracle DB. It returns the connection object, but does not return any result set. Could you please help me If I am missing anything

var JDBC = require('../../node_modules/jdbc');
var jinst = require('../../node_modules/jdbc/lib/jinst');

if (!jinst.isJvmCreated()) {
  jinst.addOption("-Xrs");
  jinst.setupClasspath(['../../jdbc_drivers/ojdbc6.jar',
                        '../../jdbc_drivers/vertica-jdk5-6.1.0-0.jar',
                        //'./drivers/derbyclient.jar',
                        //'./drivers/derbytools.jar'
                        ]);
}

var OracleConfig = {
    //for oracle database
    //libpath:      '../../jdbc_drivers/ojdbc6.jar',
    drivername:     'oracle.jdbc.driver.OracleDriver',
    url:               'jdbc:oracle:thin:QA_USER/Password_2013@//abc db01.corp.mycompany.com:1700/itenv',
};

var sqlQuery_oracle   = "select \* from Prod_LABEL where username = 'user_test30'";

var hsqldb = new JDBC(OracleConfig);

hsqldb.initialize(function(err) {
  if (err) {
    console.log("run time error is : " +err);
  }

  hsqldb.reserve(function(err, connObj) {
  // The connection returned from the pool is an object with two fields
  // {uuid: <uuid>, conn: <Connection>}
  if (connObj) {
    console.log("Using connection: " + connObj.uuid);
    // Grab the Connection for use.
    var conn = connObj.conn;

```
//function(callback) {
    // CREATE SQL.
    // Select statement example. 
```

  conn.createStatement(function(err, statement) {
    if (err) {
      callback(err);
      } else {
      console.log("the statement is : " +statement);
      statement.executeQuery(sqlQuery_oracle, function(err, resultset) {
      if (err) {
        callback(err)
      } else {
        // Convert the result set to an object array. 
        console.log("the result set is : " +resultset);
        resultset.toObjArray(function(err, results) {
          if (results.length > 0) {
            console.log("ID: " + results[0].ID);
          }
          (null, resultset);
        });
      }
    });
  }
});
}
});

});

**Comment by CraZySacX** [comment]
Closing this due to age.   Feel free to re-open if you are still having issues.
