### ISSUE TITLE
Invalid connections when DB restarts

### ISSUE THREAD

**Issue by jibin-tj** [CraZySacX/node-jdbc#107]
I use this module with teradata DB. When the DB goes restarts ,the connections becomes invalid when trying to execute statement  but still connections are in pool. I have to restart my app in order to get new connections.
Is there any config/fix for this ?

**Comment by CraZySacX** [comment]
Try using the purge function in pool.js.   You can call purge, null the existing pool reference, and the recreate the Pool as normal.   This should reset all the connections.

Also, I'm working on a connection health check to automatically refresh stale connections, but it's not ready yet.

**Comment by jibin-tj** [comment]
Thank you so much for replying. I will look into the functions you mentioned.
