### ISSUE TITLE
Why number of connections exceeds pool size in node jdbc?

### ISSUE THREAD

**Issue by vahidrahmani** [CraZySacX/node-jdbc#112]
i use pooll with minPoolsize 5 and maxPoolsize 10 
when i run code first time database connection is 5 But by repeating the code excution , number of connections increases, and even the amount is more than maxPoolsize .
after debug I realized when use `conn.createStatement` It happens but I dont understand this reason.

**Comment by jibin-tj** [comment]
It simetimes happens to me also

**Comment by vahidrahmani** [comment]
use statement.close()....
this problem solved...

**Comment by CraZySacX** [comment]
Closing per comments
