### ISSUE TITLE
How to get generated Id 

### ISSUE THREAD

**Issue by vahidrahmani** [CraZySacX/node-jdbc#114]
How to get generated Id when inserting a row into oracle .
please help me

**Comment by vahidrahmani** [comment]
i realized 
conn.prepareStatement(query,1, function (err, statement){
statement.executeUpdate(function (err, count) {
 statement.getGeneratedKeys(function (err, resultset) {
                            resultset.toObjArray(function (err, rowId) {
                                deferred.resolve({count: count, rowId: rowId[0].ROWID});
                            });
                        });
})

}

**Comment by CraZySacX** [comment]
Resolved as submitter solved.
