### ISSUE TITLE
Kerberos Authentication

### ISSUE THREAD

**Issue by ccbeloy** [CraZySacX/node-jdbc#117]
Is there any support for Kerberos authentication? How?

**Comment by grit96** [comment]
I would also like to see Kerberos support.

**Comment by grit96** [comment]
I have figured this out, you need to create a Kerberos keytab file on your system and JDBC will automatically pick it up and use it. More details [here](https://kb.iu.edu/d/aumh)

**Comment by kshitizshankar** [comment]
Could you please elaborate on how you solved this? I am trying to do something very similar...
Thanks :)

**Comment by CraZySacX** [comment]
I am not familiar with Kerberos at all, but closing as it appears there are methods that allow JDBC to use kerberos outside of adding support in the library.

If you would like support in the library, feel free to submit a pull request, or point me in the direction of how to integrate Kerberos.

**Comment by Jacodelange** [comment]
Could anybody point me in the right direction to use Kerberos Authentication with this JDBC package?

**Comment by grit96** [comment]
You don't have to do anything special to get this package working with Kerberos. You just need to setup a Kerberos keytab as detailed [here](https://kb.iu.edu/d/aumh) on your system and JDBC will automatically use it.
