### ISSUE TITLE
nextSync optimize 

### ISSUE THREAD

**Issue by dbit-xia** [CraZySacX/node-jdbc#118]
IN **resultset.js**
var nextRow = self._rs.nextSync();  //This sentence is blocked calls, it is recommended to optimize the look, thank you

**Comment by rostislavprovodenko** [comment]
any news on this?

**Comment by CraZySacX** [comment]
There are no plans to make toObjectIter process rows asynchronously.   If you need this optimization, I would recommend processing your resultsets with a custom implementation.

Feel free to submit a pull request with an async implementation if you feel so inclined.
