### ISSUE TITLE
No results were returned by the query for Netezza

### ISSUE THREAD

**Issue by pthieu** [CraZySacX/node-jdbc#119]
I'm trying to use this to connect to Netezza using Netezza's driver `nzjdbc.jar`; the connection seems to be successful but when querying a simple `SELECT *` from a table, I get the error `No results were returned by the query.`

I've invoked the same query using Aginity Workbench and confirmed that there is data so not sure why I'm getting this error.

I've followed the example code and my configuration looks like this:

```
if (!jinst.isJvmCreated()) {
  jinst.addOption("-Xrs");
  jinst.setupClasspath([path.resolve(__dirname, '..', 'drivers/nzjdbc3.jar'), ]);
}

var netezza = new JDBC({
  url: [
    'jdbc:netezza://<hostname>/<DBNAME>;',
    'user=', config.nz_user, ';',
    'password=', config.nz_password, ';',
  ].join(''),
  drivername: 'org.netezza.Driver',
  minpoolsize: 5,
  maxpoolsize: 10
});
```

```
node -v && npm -v
v4.4.6
2.15.5
```

**UPDATE 5/10/16**:
Looks like it works if I write a quick java method to invoke a `SELECT` using the `.jar`. Leads me to believe the issue is either in the `jdbc` or the `java` module.

Was playing around in REPL, invoked `rs.getMetaData()` then `rsmt.getColumnCount` and `rsmt.getColumnName` and looks like the columns are correct. Not sure why data isn't returned. `rs.next()` returns false.

Let me know if you need any more information.

**Comment by CraZySacX** [comment]
Closing due to age.   Feel free to re-open if this is still an issue.
