### ISSUE TITLE
Response limit exceeded

### ISSUE THREAD

**Issue by pberden** [CraZySacX/node-jdbc#123]
Hi, I'm using node-jdbc to query a Teradata database. After initializing the connection, I always get the following error after I've used a connection from the pool 16 times: 
```
[TeraJDBC 15.10.00.14] [Error 3130] [SQLState HY000] Response limit exceeded.
```
It turns out that this Teradata error means that the connections are not closed properly. http://stackoverflow.com/questions/18903284/teradata-database-3130-response-limit-exceeded

I use the release method to return the connection to the pool. But I wonder, is this then not the same thing as closing the connection? I call the release method like so:
```
function _release(connObj) {

    teradb.release(connObj, function(err) {
        if(config.verbose) {
            chalksay.green('Releasing connection: ' + connObj.uuid);
        }
        if (err) {
            chalksay.red(err.message);
        }
    });
}
```
See attached the complete connection setup.

[jdbc-connect.txt](https://github.com/CraZySacX/node-jdbc/files/742209/jdbc-connect.txt)

**Comment by CraZySacX** [comment]
When you release a connection back to the pool, the connection is not
closed.  The pool maintains a set of open connections to avoid the overhead
of opening/closing for each query.   There are some API calls you can use
to refresh the pool to force close the connections.

**Comment by pberden** [comment]
Are you referring to the close method in connection.js?

**Comment by CraZySacX** [comment]
Take a look at [purge](https://github.com/CraZySacX/node-jdbc/blob/master/lib/pool.js#L243) in pool.js.   That will forcefully close all the connections in the pool.  You can use initialize to re-open them.

**Comment by pberden** [comment]
Thanks! I was using the maxidle in the configuration. But I was still on an older version of node-jdbc and therefore it had no effect. Now I'm on 0.4.0, and it is working as expected!
