### ISSUE TITLE
Numbers are returned as an object

### ISSUE THREAD

**Issue by pberden** [CraZySacX/node-jdbc#124]
I just upgrade from node-jdbc 0.1.0 to 0.4.0, see issue [https://github.com/CraZySacX/node-jdbc/issues/123](url)

Now the result set gives me objects instead of numeric values for some of the numerical fields that I use in my SQL statement. See the result set:

```
{
"month$id": {},
"month$name": "200506",
"amount": {},
"avg_curr_open_days": 936.3107299804688
}
```

And the executed SQL:
```
SELECT 
    _time.CALENDAR_MONTH_NUMBER AS month$id,
    _time.CALENDAR_MONTH_NAME AS month$name,
    SUM(ap.AMOUNT) AS amount,
    AVG(ap.CURRENTLY_OPEN_DAYS) AS avg_curr_open_days
FROM CAP_ACCNTS_PAYABLE_OVERVIEW ap
LEFT JOIN D_TIME _time
    ON (...)
GROUP BY 1,2
```

Is this somehow related to [https://github.com/CraZySacX/node-jdbc/issues/100](url)?

**Comment by CraZySacX** [comment]
Possibly.   Depends on the sql datatypes of those fields.

In order to extract the values from the return results I end up doing something like the following:

```
       resultset.toObjArray(function(err, results) {
          if (err) return releasefn(err, null, callback);
          mapValues(results, function(err, results) {
            if (err) return releasefn(err, null, callback);
            return releasefn(null, results, callback);
          })
        });
```

where mapValues looks like

```
function mapValues(results, callback) {
  var mapped = results.map(function(result) {
    return _.mapValues(result, function (v, k) {
      switch (k) {
        case 'FIELD_1':
        case 'FIELD_2':
        case 'FIELD_3':
          return v.intValueSync();
          break;
        case 'FIELD_4':
        case 'FIELD_5':
          return v.doubleValueSync();
          break;
        default:
          return db.safetrim(v);
          break;
      };
    });
  });
  callback(null, mapped)
}
```

The xValueSync calls are actually calls into the Java API to extract the value from the wrapped java type.

**Comment by pberden** [comment]
Thanks, I will try this out next week.

I expect I need to update the `FIELD_X` values to my situation? But I'm clueless...I don't expect these to be the names from the SQL statement like `month$id` and `amount`, right? Should these be like `DECIMAL` and `NUMERIC`? If so, should I be looking into the [Teradata JDBC API](https://developer.teradata.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_2.html#CCHNUMBR)?

**Comment by CraZySacX** [comment]
They should be the ```month$id``` and ```amount``` field names (or whatever you alias them to).    

If they are ```NUMERIC``` or ```DECIMAL``` sql datatypes, they will be wrapped in a [java.math.BigDecimal](http://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html).  Calling ```intValueSync```  or ```doubleValueSync``` will extract the relevant value out of the BigDecimal as a javascript number.   

The 'Sync' suffix on the above functions indicate that you wish to wait for the result.  The node-java API exposes both the asynchronous version of the method (as ```intValue```) and the synchronous version with the 'Sync' suffix (```intValueSync```).  Under the covers, both functions end up calling the intValue method on the object (in this case BigDecimal).

**Comment by pberden** [comment]
Thanks Jason, I got it to work. However in my application I don't always know upfront the type of the field that is returned by the SQL statement. So this is not desirable functionality in my case.

What caused this to change form 0.1.0 to 0.4.0? Is there any way to have the `toObjArray` behave like it did in 0.1.0?

**Comment by pberden** [comment]
For anyone asking the same question: I use the following code to extract doubles out of any BigDecimals being returned by the database. I'm not sure if the `if(cell !== null && typeof cell === 'object')` is returning true for values that are not BigDecimals. Up till now it seems to be working fine for the queries that I need.
`
resultset.toObjArray(function (err, results) {
  // Map through resultset to see if BigDecimals need data extraction
  results = results.map((row) => {
    return _.mapValues(row, (cell) => {
      if(cell !== null && typeof cell === 'object') {
        return cell.doubleValueSync();
      } else { return cell; }
    });
  });
  statement.close(function (err) {
    if (err) { return reject(err); }
  });
  _release(connObj);
  return resolve(results);
});`

**Comment by r3wt** [comment]
Over 3 years later, and facing this problem. i think this is a safer approach, where `obj` is a database row in the `resultSet` and `k` is a given field:
```js
if(obj[k] !==null && typeof obj[k]==='object'){
  const type = Object.prototype.toString.call(obj[k]).slice(8, -1);
  if(type==='nodeJava_java_math_BigDecimal') {
    obj[k] = obj[k].doubleValueSync();
  }
}
```
