### ISSUE TITLE
ORM for jdbc npm?

### ISSUE THREAD

**Issue by aaronbartell** [CraZySacX/node-jdbc#125]
Does anyone know if an ORM exists for this jdbc npm?  

Been looking for awhile and it seems most (all?) ORMs only support PostgreSQL and/or MySQL as far as relational databases go.

**Comment by CraZySacX** [comment]
I don't know of any off hand, but you may want to look through the node-jdbc [dependents list](https://docs.oracle.com/javase/tutorial/jdbc/basics/transactions.html) to see if any pop up.
