### ISSUE TITLE
Ask to Install JRE 1.6

### ISSUE THREAD

**Issue by toadead** [CraZySacX/node-jdbc#126]
Anyone knows why it ask me to install legacy JRE 1.6?

**Comment by stuartking** [comment]
I ran into the same issue (on OSX) which is related to the node-java module. The solution that worked for me is here: https://github.com/joeferner/node-java/issues/90#issuecomment-45613235

**Comment by CraZySacX** [comment]
Closing.  Issue should be reopened in node-java project if it is still an issue.
