### ISSUE TITLE
Not able to install node-jdbc

### ISSUE THREAD

**Issue by rentasad** [CraZySacX/node-jdbc#130]
Hi,

I try to install node-jdbc on different PCs - windows 10, windows 7,... I get the following error:

> > C:\Development\projects\restserver>npm install --save jdbc
> 
> > java@0.8.0 install C:\Development\projects\restserver\node_modules\java
> > node-gyp rebuild
> 
> 
> C:\Development\projects\restserver\node_modules\java>if not defined npm_config_n
> ode_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\
> node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parall
> ele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
> C:\Development\projects\restserver\node_modules\java\build\nodejavabridge_bindi
> ngs.vcxproj(19,3): error MSB4019: Das importierte Projekt "C:\Microsoft.Cpp.Def
> ault.props" wurde nicht gefunden. Vergewissern Sie sich, dass der Pfad in der <
> Import>-Deklaration korrekt und die Datei auf dem Datenträger vorhanden ist.
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
> ` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
> npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
> s.js:215:12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
> s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Development\projects\restserver\node_modules\java
> gyp ERR! node -v v6.10.2
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> npm WARN restserver@1.0.0 No description
> npm WARN restserver@1.0.0 No repository field.
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
> node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "jdbc"
> npm ERR! node v6.10.2
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! java@0.8.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the java@0.8.0 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the java package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs java
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls java
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Development\projects\restserver\npm-debug.log
> 
> C:\Development\projects\restserver>

Have you an idea for a reason about this error?

**Comment by CraZySacX** [comment]
I don't sorry.  You may want to open an issue over on the [node-java](https://github.com/joeferner/node-java) repository, as this is an issue building that dependency.

**Comment by rentasad** [comment]
Hi CrazySack,

thanks for you fast reply - sorry Im tried many steps to find a solution. npm install -g jdbc I get the same Error:

> C:\Development\projects\restserver>npm install -g jdbc
> 
> > java@0.8.0 install C:\Users\adm.mst\AppData\Roaming\npm\node_modules\jdbc\node
> _modules\java
> > node-gyp rebuild
> 
> 
> C:\Users\adm.mst\AppData\Roaming\npm\node_modules\jdbc\node_modules\java>if not
> defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\
> node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
>  "" rebuild )
> Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parall
> ele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
> C:\Users\adm.mst\AppData\Roaming\npm\node_modules\jdbc\node_modules\java\build\
> nodejavabridge_bindings.vcxproj(19,3): error MSB4019: Das importierte Projekt "
> C:\Microsoft.Cpp.Default.props" wurde nicht gefunden. Vergewissern Sie sich, da
> ss der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datenträg
> er vorhanden ist.
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
> ` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
> npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
> s.js:215:12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
> s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\adm.mst\AppData\Roaming\npm\node_modules\jdbc\node_modules
> \java
> gyp ERR! node -v v6.10.2
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> C:\Users\adm.mst\AppData\Roaming\npm
> `-- (empty)
> 
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
> node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "jdbc"
> npm ERR! node v6.10.2
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! java@0.8.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the java@0.8.0 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the java package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs java
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls java
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Development\projects\restserver\npm-debug.log
> npm ERR! code 1

Do you have any Idea?
Best regards

Matthias

**Comment by rentasad** [comment]
Hi,
in Linux I solved my Problem - you can close this case.
Best regards
Matthias
