### ISSUE TITLE
Executed query returning Java_java_math_BigDecimal for all number columns

### ISSUE THREAD

**Issue by YeeP79** [CraZySacX/node-jdbc#132]
Is there a way I can handle the BigDecimal data type that is apparently returned by my query?

query:
`SELECT * FROM IVR_LZ_CALL_LEG WHERE ROWNUM < 10`

table 'describe' in Oracle:
```
Name                          Null?    Type          
----------------------------- -------- ------------- 
CALL_DATE                     NOT NULL DATE          
CALL_LEG_ID                   NOT NULL NUMBER(25)    
START_TS                      NOT NULL TIMESTAMP(6)  
END_TS                        NOT NULL TIMESTAMP(6)  
ELAPSED_MSEC                           NUMBER(9)     
ROUTER_CALL_DAY                        NUMBER(9)     
ROUTER_CALL_KEY                        NUMBER(9)     
LANGUAGE_TYPE                          VARCHAR2(20)
```

code snippet being executed:
```
conn.createStatement(function (err, smnt) {
    if(err) {
        cb(err);
    } else {
        smnt.executeQuery(query, function (err, results) {
            if(err) {
                cb(err);
            } else {
                if(results) {
                    results.toObjArray(function (err, res) {
                        console.log(res);//DEBUG
                        cb(null, res);
                    });
                } else {
                    cb(null);
                }
            }
        });
    }
});
```

example 'console logged' data:
```
 { CALL_DATE: '2012-10-17 00:00:00.0',
    CALL_LEG_ID: nodeJava_java_math_BigDecimal {},
    START_TS: '2012-10-17 17:26:12.169',
    END_TS: '2012-10-17 17:27:52.104',
    ELAPSED_MSEC: nodeJava_java_math_BigDecimal {},
    ROUTER_CALL_DAY: nodeJava_java_math_BigDecimal {},
    ROUTER_CALL_KEY: nodeJava_java_math_BigDecimal {},
    LANGUAGE_TYPE: 'ENGLISH',
```

What this data actually looks like in the DB;
```
CALL_DATE: 21-DEC-16	
 CALL_LEG_ID: 922472020034540000553869	
 START_TS: 21-DEC-16 12.34.54.868000000 AM	
 END_TS: 21-DEC-16 12.36.42.930000000 AM	
 ELAPSED_MSEC: 108062	
 ROUTER_CALL_DAY: 151930	
 ROUTER_CALL_KEY: 3906	
 LANGUAGE_TYPE: ENGLISH
```	

Any help in this would be much appreciated.
Thank you

**Comment by CraZySacX** [comment]
Take a look at the last couple comments here: https://github.com/CraZySacX/node-jdbc/issues/100

They describe how to handle the data types.

I'll update the docs to show this, seems to be a common question.

**Comment by YeeP79** [comment]
Thank you for the quick response. Looking into that now.

**Comment by YeeP79** [comment]
Jason, I wrote an iterator to roll through the object and evalate each key,
but I am not sure the best way to test of the object is a big decimal, if
so convert. Any ideas?

**Comment by YeeP79** [comment]
So I have expanded the original code given to the following, but I still do not see an integer. Do I need to include a Java class?

```
smnt.executeQuery(query, function (err, results) {
    if(err) {
        cb(err);
    } else {
        if(results) {
            results.toObjArray(function (err, res) {
                res.forEach(function(obj){
                    Object.keys(obj).forEach(function(element, index){
                        let value = obj[Object.keys(obj)[index]];
                        console.log(element); //DEBUG
                        console.log(value); //DEBUG
                        if(typeof(value) === 'object'){
                            value.intValue(function(err, intVal) {
                                if(err){
                                    console.log("error: " + err); //DEBUG
                                } else {
                                    console.log(intVal); //DEBUG
                                }
                            })
                        }
                    });
                })
                cb(null, res);
            });
        } else {
            cb(null);
        }
    }
});
```

**Comment by sandeepvedavyas** [comment]
I have faced the same issue , later I found a workaround with sqlResultSet[0].propertyName.
floatValueSync());. I also found methods like toString(),floatValue,intValue() but floatvalue() and intValue gives error like "Method 'floatValue' called without a callback did you mean to use the Sync version?" So i have used floatValueSync() method  in my case to get a float value.

**Comment by fasidOnGit** [comment]
@sandeepvedavyas @YeeP79   Try JSON.parse to that key which is giving you nodeJava_java_math_BigDecimal {}

In Your case. For Ex :
`var result = {
CALL_DATE: '2012-10-17 00:00:00.0',
    CALL_LEG_ID: nodeJava_java_math_BigDecimal {},
    START_TS: '2012-10-17 17:26:12.169',
    END_TS: '2012-10-17 17:27:52.104',
    ELAPSED_MSEC: nodeJava_java_math_BigDecimal {},
    ROUTER_CALL_DAY: nodeJava_java_math_BigDecimal {},
    ROUTER_CALL_KEY: nodeJava_java_math_BigDecimal {},
    LANGUAGE_TYPE: 'ENGLISH',
}
console.log(JSON.parse(result.ROUTER_CALL_DAY));`

**Comment by CraZySacX** [comment]
Closing.  The regular java API allows you to get the appropriate values.
