### ISSUE TITLE
Connection Pool not released

### ISSUE THREAD

**Issue by dnnyz** [CraZySacX/node-jdbc#133]
Hi Jason, 
I used your example and I still see opened connections in DB.
This is my configuration:
minpoolsize: 0,
maxpoolsize: 55,
maxidle: 1000,

It looks like the maxidle is not working.

**Comment by CraZySacX** [comment]
max idle is not intended to close the connection.  The feature allows you to monitor for stale connections and reopen new ones after an duration of `maxidle` has passed.
