### ISSUE TITLE
Does this package support JDBC connections that require a httpPath?

### ISSUE THREAD

**Issue by johnwalker2000** [CraZySacX/node-jdbc#143]
Does this driver support a JDBC endpoint that requires specification of the httpPath like the one below?

jdbc:hive2://servername:443/default;transportMode=http;ssl=true;httpPath=sql/protocolv1/o/0/0826-153058-snub8

**Comment by CraZySacX** [comment]
It should, however I've never tested a driver that requires it.

Try
```
var hive = new JDBC({
  url: 'jdbc:hive2://servername:443/default;transportMode=http;ssl=true;httpPath=sql/protocolv1/o/0/0826-153058-snub8',
  minpoolsize: 5,
  maxpoolsize: 10
});
```

also the following may work

```
var hive = new JDBC({
  url: 'jdbc:hive2://servername:443/default'
  minpoolsize: 5,
  maxpoolsize: 10,
  properties: {
      transportMode: 'http',
      ssl='true',
      httpPath='sql/protocolv1/o/0/0826-153058-snub8'
  }
});

**Comment by johnwalker2000** [comment]
Thank you very much. Will try soon!

**Comment by johnwalker2000** [comment]
Got the top link working with Databricks Spark!

**Comment by CraZySacX** [comment]
Closing as resolved.
