### ISSUE TITLE
no suitable driver found.

### ISSUE THREAD

**Issue by camwes** [CraZySacX/node-jdbc#144]
I am attempting to connect to a server and am getting the following error:
`No suitable driver found for jdbc:as400://x.x.x.x/`
I have downloaded the jt400.jar and added to my project, and despite adding the driver to the app I still cannot connect:
```
if (!jinst.isJvmCreated()) {
  jinst.addOption("-Xrs");
  jinst.setupClasspath(['./../../drivers/jt400.jar']);
}
```

**Comment by CraZySacX** [comment]
Try adding the drivername to your db config object.   The drivername is optional except when using an old style JDBC driver.   My hunch is jt400.jar is old style and adding the drivername should fix your issue.   On a side note, the AS/400 JDBC drivers were the first I ever used.  Thanks for the memories :).

```
var config = {
  // Required
  url: 'jdbc:as400://x.x.x.x',

  // Optional
  drivername: 'com.ibm.as400.access.AS400JDBCDriver',
  user: '<username>',
  password: '<password>',
  properties: {}
};
```

**Comment by camwes** [comment]
thanks for the quick reply, this driver really are a blast from the past. Unfortunately, adding the drivername did not make a difference. I've used this url to connect to the instance via sqirrel sql, so I'm not very sure whats missing.

**Comment by camwes** [comment]
I did some reorganizing and was eventually able to get the driver to work, I'm assuming the drivername did solve the problem. Thanks again for your help
