### ISSUE TITLE
ResultSetMetaData getColumn 

### ISSUE THREAD

**Issue by AchrafLansari** [CraZySacX/node-jdbc#145]
log is undefined on line 17 : 

log.debug('getColumnCount ERR!!!', err);

**Comment by jmargaglione** [comment]
Similar:

[2017-10-26T23:04:36.374Z]  INFO: outlaw-server/69800 on HAL9001: Found undefined
C:\Users\john\Projects\outlaw\outlaw-server\node_modules\jdbc\lib\resultsetmetadata.js:17
      log.debug('getColumnCount ERR!!!', err);

Just doing a simple select from a view:

stmt.executeQuery(`SELECT * FROM V_FIRM_LATEST WHERE _firmId = '${firmId}'`)

**Comment by jmargaglione** [comment]
OK, backtracked it to a missing callback, which in my case was caused by Promisifying the code but not realizing that toObjArray had a callback.  So you might want to make sure you have your callbacks set up right.

Either way that log code needs to be removed.

**Comment by CraZySacX** [comment]
Ah, good catch.  That came in on a pull request and I missed it.  I'll remove it tomorrow.

**Comment by Nocturnal316** [comment]
Was this ever officially removed? I'm running into the same issue

**Comment by CraZySacX** [comment]
The `console.log` has been removed in 0.6.1.
