### ISSUE TITLE
Cannot find module nodejavabridge_bindings.node

### ISSUE THREAD

**Issue by stianbranden** [CraZySacX/node-jdbc#147]
Hi, 

I`m running jdbc on a RHEL 6 server and getting the following error message:
![image](https://user-images.githubusercontent.com/20839659/32367150-6e2140d2-c081-11e7-9b60-1ee084c67d45.png)

Java (and Javac) version is 1.8.0_152
Node version is 6.11.5
Npm version is 3.10.10

I`ve tested the same setup on my windows 10 computer which works.
Can anybody help?

SB

**Comment by CraZySacX** [comment]
Take a look at #149.  That has some comments that may lead to a solution.

**Comment by CraZySacX** [comment]
Closing as this is an error building a dependency.   If this is still an issue, please open a ticket in the [node-java](https://github.com/joeferner/node-java) project.
