### ISSUE TITLE
 [java] # C  [libacml.so+0x1a06dfd]  __intel_new_memset+0xa8d

### ISSUE THREAD

**Issue by rajulm** [CraZySacX/node-jdbc#150]
A fatal error has been detected by the Java Runtime Environment:
     [java] #
     [java] #  SIGSEGV (0xb) at pc=0x00007fce2fd25dfd, pid=120131, tid=0x00007fce1f354700
     [java] #
     [java] # JRE version: OpenJDK Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
     [java] # Java VM: OpenJDK 64-Bit Server VM (25.144-b01 mixed mode linux-amd64 compressed oops)
     [java] # Problematic frame:
     [java] # C  [libacml.so+0x1a06dfd]  __intel_new_memset+0xa8d

**Comment by rajulm** [comment]
I am sorry I should have reported this issue in C-Java. Looks like the issue is while calling the C functions from the java libraries.

**Comment by CraZySacX** [comment]
Sure, https://github.com/joeferner/node-java

Closing this for now as it should be opened in that project.   Feel free to re-open if its related to node-jdbc.
