### ISSUE TITLE
A fatal error in JVM while running nodejs app

### ISSUE THREAD

**Issue by mrkshaw** [CraZySacX/node-jdbc#153]
I am running a nodejs app having jdbc dependency on alpine linux os  for arm32v6 architecture(raspberry pi 3). After installing all dependencies when I try to run application its showing me below error: 

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (os_linux.cpp:4875), pid=2660, tid=0x76f0c4d8
#  guarantee(polling_page != MAP_FAILED) failed: os::init_2: failed to allocate polling page
#
# JRE version:  (8.0_151-b12) (build )
# Java VM: Java HotSpot(TM) Server VM (25.151-b12 mixed mode linux-arm )
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /SOSLiteServer/hs_err_pid2660.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Illegal instruction

please help..

**Comment by CraZySacX** [comment]
I'm going to need more information.  Can you enable core dumps or dig into that hs_err_pid2660.log file?

**Comment by mrkshaw** [comment]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (os_linux.cpp:4875), pid=470, tid=0x76fca4d8
#  guarantee(polling_page != MAP_FAILED) failed: os::init_2: failed to allocate polling page
#
# JRE version:  (8.0_151-b12) (build )
# Java VM: Java HotSpot(TM) Server VM (25.151-b12 mixed mode linux-arm )
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread is native thread

Stack: [0x7edcf000,0x7edf1000]

---------------  P R O C E S S  ---------------

VM state:not at safepoint (not fully initialized)

VM Mutex/Monitor currently owned by a thread: None


Dynamic libraries:
20480000-20500000 rw-p 00000000 00:00 0 
20f80000-20f85000 rw-p 00000000 00:00 0 
20f85000-20f86000 ---p 00000000 00:00 0 
20f86000-20fa7000 rwxp 00000000 00:00 0 
20fa7000-20fa8000 ---p 00000000 00:00 0 
21c00000-21c05000 rw-p 00000000 00:00 0 
21c05000-21c06000 ---p 00000000 00:00 0 
21c06000-21c30000 rwxp 00000000 00:00 0 
21c30000-21c31000 ---p 00000000 00:00 0 
23380000-23400000 rw-p 00000000 00:00 0 
28000000-28080000 rw-p 00000000 00:00 0 
2c380000-2c48c000 rw-p 00000000 00:00 0 
2dd00000-2dd80000 rw-p 00000000 00:00 0 
2e380000-2e400000 rw-p 00000000 00:00 0 
312ec000-312f0000 rw-p 00000000 00:00 0 
312f0000-312f2000 ---p 00000000 00:00 0 
31c00000-31c80000 rw-p 00000000 00:00 0 
33980000-33a00000 rw-p 00000000 00:00 0 
36200000-36205000 rw-p 00000000 00:00 0 
36205000-36206000 ---p 00000000 00:00 0 
36206000-36207000 rwxp 00000000 00:00 0 
36207000-36208000 ---p 00000000 00:00 0 
36700000-36780000 rw-p 00000000 00:00 0 
36e00000-36e80000 rw-p 00000000 00:00 0 
37f80000-38000000 rw-p 00000000 00:00 0 
38f80000-38f85000 rw-p 00000000 00:00 0 
38f85000-38f86000 ---p 00000000 00:00 0 
38f86000-38fa7000 rwxp 00000000 00:00 0 
38fa7000-38fa8000 ---p 00000000 00:00 0 
39c00000-39c05000 rw-p 00000000 00:00 0 
39c05000-39c06000 ---p 00000000 00:00 0 
39c06000-39c07000 rwxp 00000000 00:00 0 
39c07000-39c08000 ---p 00000000 00:00 0 
3a480000-3a500000 rw-p 00000000 00:00 0 
3a800000-3a880000 rw-p 00000000 00:00 0 
3b600000-3b606000 rw-p 00000000 00:00 0 
3ce00000-3ce05000 rw-p 00000000 00:00 0 
3ce05000-3ce06000 ---p 00000000 00:00 0 
3ce06000-3ce27000 rwxp 00000000 00:00 0 
3ce27000-3ce28000 ---p 00000000 00:00 0 
41080000-41100000 rw-p 00000000 00:00 0 
42780000-42800000 rw-p 00000000 00:00 0 
43b00000-43b36000 rw-p 00000000 00:00 0 
44b80000-44c00000 rw-p 00000000 00:00 0 
48e80000-48f00000 rw-p 00000000 00:00 0 
4a500000-4a580000 rw-p 00000000 00:00 0 
4cb80000-4cc00000 rw-p 00000000 00:00 0 
51880000-51885000 rw-p 00000000 00:00 0 
51885000-51886000 ---p 00000000 00:00 0 
51886000-518ff000 rwxp 00000000 00:00 0 
518ff000-51900000 ---p 00000000 00:00 0 
51b80000-51c00000 rw-p 00000000 00:00 0 
53900000-53905000 rw-p 00000000 00:00 0 
53905000-53906000 ---p 00000000 00:00 0 
53906000-5397f000 rwxp 00000000 00:00 0 
5397f000-53980000 ---p 00000000 00:00 0 
53c80000-53d00000 rw-p 00000000 00:00 0 
54800000-54880000 rw-p 00000000 00:00 0 
54b47000-55d92000 r-xp 00000000 00:2b 70         /usr/bin/node
55da2000-55dd6000 r--p 0124b000 00:2b 70         /usr/bin/node
55dd6000-55ddc000 rw-p 0127f000 00:2b 70         /usr/bin/node
55ddc000-55de8000 rw-p 00000000 00:00 0 
577b3000-578fa000 rw-p 00000000 00:00 0          [heap]
59780000-59800000 rw-p 00000000 00:00 0 
5bd00000-5be0c000 rw-p 00000000 00:00 0 
5d400000-5d480000 rw-p 00000000 00:00 0 
5fd00000-5fd80000 rw-p 00000000 00:00 0 
73756000-73a57000 rw-p 00000000 00:00 0 
73a57000-74201000 r-xp 00000000 00:2b 6324       /opt/jdk-8u151-b12/jre/lib/arm/server/libjvm.so
74201000-74256000 rw-p 007a2000 00:2b 6324       /opt/jdk-8u151-b12/jre/lib/arm/server/libjvm.so
74256000-74700000 rw-p 00000000 00:00 0 
74800000-74880000 rw-p 00000000 00:00 0 
748d4000-748ff000 r-xp 00000000 00:2b 6516       /opt/jdk-8u151-b12/jre/lib/arm/libjava.so
748ff000-74900000 rw-p 00023000 00:2b 6516       /opt/jdk-8u151-b12/jre/lib/arm/libjava.so
74900000-74980000 rw-p 00000000 00:00 0 
7499a000-749c9000 r-xp 00000000 00:2b 5253       /lib/ld-linux-armhf.so.3
749c9000-749ca000 r--p 0001f000 00:2b 5253       /lib/ld-linux-armhf.so.3
749ca000-749cb000 rw-p 00020000 00:2b 5253       /lib/ld-linux-armhf.so.3
749cb000-749fe000 r-xp 00000000 00:2b 6319       /SOSLiteServer/node_modules/java/build/Release/nodejavabridge_bindings.node
749fe000-749ff000 r--p 00023000 00:2b 6319       /SOSLiteServer/node_modules/java/build/Release/nodejavabridge_bindings.node
749ff000-74a00000 rw-p 00024000 00:2b 6319       /SOSLiteServer/node_modules/java/build/Release/nodejavabridge_bindings.node
74a00000-74a80000 rw-p 00000000 00:00 0 
74a93000-74aa4000 r-xp 00000000 00:2b 6496       /opt/jdk-8u151-b12/jre/lib/arm/libverify.so
74aa4000-74aa5000 rw-p 00009000 00:2b 6496       /opt/jdk-8u151-b12/jre/lib/arm/libverify.so
74aa5000-74b05000 rw-p 00000000 00:00 0 
74b05000-74b06000 ---p 00000000 00:00 0 
74b06000-74b7f000 rwxp 00000000 00:00 0 
74b7f000-74b80000 ---p 00000000 00:00 0 
74b81000-74b83000 ---p 00000000 00:00 0 
74b83000-75384000 rw-p 00000000 00:00 0 
75384000-75386000 ---p 00000000 00:00 0 
75386000-75b87000 rw-p 00000000 00:00 0 
75b87000-75b89000 ---p 00000000 00:00 0 
75b89000-7638a000 rw-p 00000000 00:00 0 
7638a000-7638c000 ---p 00000000 00:00 0 
7638c000-76b8d000 rw-p 00000000 00:00 0 
76b8d000-76bb9000 r-xp 00000000 00:2b 83         /lib/libgcc_s.so.1
76bb9000-76bba000 rw-p 0001c000 00:2b 83         /lib/libgcc_s.so.1
76bba000-76cd1000 r-xp 00000000 00:2b 82         /usr/lib/libstdc++.so.6.0.22
76cd1000-76cd8000 r--p 00107000 00:2b 82         /usr/lib/libstdc++.so.6.0.22
76cd8000-76cd9000 rw-p 0010e000 00:2b 82         /usr/lib/libstdc++.so.6.0.22
76cd9000-76cdb000 rw-p 00000000 00:00 0 
76cdb000-76d3b000 r-xp 00000000 00:2b 80         /lib/libssl.so.1.0.0
76d3b000-76d3e000 r--p 00050000 00:2b 80         /lib/libssl.so.1.0.0
76d3e000-76d41000 rw-p 00053000 00:2b 80         /lib/libssl.so.1.0.0
76d41000-76e90000 r-xp 00000000 00:2b 79         /lib/libcrypto.so.1.0.0
76e90000-76e9f000 r--p 0013f000 00:2b 79         /lib/libcrypto.so.1.0.0
76e9f000-76ea5000 rw-p 0014e000 00:2b 79         /lib/libcrypto.so.1.0.0
76ea5000-76ea8000 rw-p 00000000 00:00 0 
76ea8000-76ec5000 r-xp 00000000 00:2b 78         /usr/lib/libcares.so.2.2.0
76ec5000-76ec6000 r--p 0000d000 00:2b 78         /usr/lib/libcares.so.2.2.0
76ec6000-76ec7000 rw-p 0000e000 00:2b 78         /usr/lib/libcares.so.2.2.0
76ec7000-76ef4000 r-xp 00000000 00:2b 76         /usr/lib/libuv.so.1.0.0
76ef4000-76ef5000 r--p 0001d000 00:2b 76         /usr/lib/libuv.so.1.0.0
76ef5000-76ef6000 rw-p 0001e000 00:2b 76         /usr/lib/libuv.so.1.0.0
76ef6000-76f0c000 r-xp 00000000 00:2b 74         /usr/lib/libhttp_parser.so.2.7.1
76f0c000-76f0d000 r--p 00006000 00:2b 74         /usr/lib/libhttp_parser.so.2.7.1
76f0d000-76f0e000 rw-p 00007000 00:2b 74         /usr/lib/libhttp_parser.so.2.7.1
76f0e000-76f31000 r-xp 00000000 00:2b 72         /lib/libz.so.1.2.11
76f31000-76f32000 r--p 00013000 00:2b 72         /lib/libz.so.1.2.11
76f32000-76f33000 rw-p 00014000 00:2b 72         /lib/libz.so.1.2.11
76f33000-76fb9000 r-xp 00000000 00:2b 24         /lib/ld-musl-armhf.so.1
76fc3000-76fc5000 ---p 00000000 00:00 0 
76fc5000-76fc6000 rw-p 00000000 00:00 0 
76fc6000-76fc8000 r-xp 00000000 00:00 0 
76fc8000-76fca000 rw-p 00085000 00:2b 24         /lib/ld-musl-armhf.so.1
76fca000-76fcc000 rw-p 00000000 00:00 0 
7edd0000-7edf1000 rw-p 00000000 00:00 0          [stack]
7ee23000-7ee24000 r-xp 00000000 00:00 0          [sigpage]
7ee24000-7ee25000 r--p 00000000 00:00 0          [vvar]
7ee25000-7ee26000 r-xp 00000000 00:00 0          [vdso]
ffff0000-ffff1000 r-xp 00000000 00:00 0          [vectors]

VM Arguments:
jvm_args: -Xrs -Xrs -Xrs -Xrs 
java_command: <unknown>
java_class_path (initial): /SOSLiteServer/node_modules/java/commons-lang3-node-java.jar:/SOSLiteServer/node_modules/java/src-java:/h2/bin/h2-1.4.196.jar
Launcher Type: generic

Environment Variables:
JAVA_HOME=/opt/jdk-8u151-b12
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jdk/bin:/opt/jdk/bin:/opt/jdk-8u1/bin:/opt/jdk-8u151-b12/bin:/opt/jdk/jre/lib/arm/client

Signal Handlers:
SIGSEGV: [libjvm.so+0x7158a8], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGBUS: [libjvm.so+0x7158a8], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGFPE: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGPIPE: SIG_IGN, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGXFSZ: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGILL: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGUSR1: [node+0xa22388], sa_mask[0]=11111111011111111101111111111110, sa_flags=none
SIGUSR2: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGHUP: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGINT: [node+0x9b7104], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESETHAND
SIGTERM: [node+0x9b7104], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESETHAND
SIGQUIT: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none


---------------  S Y S T E M  ---------------

OS:NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.6.2
PRETTY_NAME="Alpine Linux v3.6"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"

uname:Linux 4.4.0-1030-raspi2 #37-Ubuntu SMP Thu Oct 20 15:06:25 UTC 2016 armv7l
libc:(null) (null) (fixed stack)
rlimit: STACK 8192k, CORE 0k, NPROC 7265, NOFILE 4096, AS infinity

[error occurred during error reporting (printing OS information), id 0xb]

CPU:total 4 (initial active 4) 

/proc/cpuinfo:
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 76.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 76.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 76.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 76.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2709
Revision	: a22082
Serial		: 000000004ddabd1a


Memory: 4k page, physical 942124k(377332k free), swap 0k(0k free)

vm_info: Java HotSpot(TM) Server VM (25.151-b12) for linux-arm-vfp-hflt JRE (1.8.0_151-b12), built on Sep  5 2017 19:45:55 by "java_re" with gcc 4.7.2 20120910 (prerelease)

time: Wed Dec  6 06:39:57 2017
elapsed time: 0 seconds (0d 0h 0m 0s)

**Comment by mrkshaw** [comment]
Reply please

**Comment by CraZySacX** [comment]
A quick jump into some java source (https://searchcode.com/codesearch/view/17979676/  line 4385) shows this error happening because a call to `linux_mprotect` is failing to mark a block of memory as read only.  I would dig into why that can happen on your arm architecture.   I'm closing this as it's outside the scope of node-jdbc.
