### ISSUE TITLE
Incorrect Type mapping for BIGINT

### ISSUE THREAD

**Issue by geojins** [CraZySacX/node-jdbc#154]
When the resultSet contains a BIGINT column, it is mapped to String in the final result.  Noticed that in lib/resultset.js, BIGINT mapps to String. 

https://github.com/CraZySacX/node-jdbc/blob/de398a810f19bfcc77617f6f68866daaa1eb5fae/lib/resultset.js#L30

**Comment by CraZySacX** [comment]
This was changed to `String` with 3273a82d67764d04a9112b58b4dd0e646b545466 to avoid possible truncation when trying to convert to a long.   There are Javascript libraries [BigInteger.js](https://github.com/peterolson/BigInteger.js) that can help with working with theses large values.
