### ISSUE TITLE
Decimal values are not properly returned in the result

### ISSUE THREAD

**Issue by geojins** [CraZySacX/node-jdbc#155]
When DECIMAL fields are selected in a query, output shows value as empty object ({}). 

Steps to reproduce:

- Create a table with DECIMAL field ( I am using Apache Phoenix table)
- Insert records into this table with DECIMAL values
- Issue a query using node-jdbc
- Apply resultSet.toObjectArray()
- Print results using JSON.stringify

The DECIMAL fields are displayed as {}

```code
{
            "ID": "1",
            "BIGDECIMAL1": {}           
        }
``` 
In lib/resultset.js , If i explicitly convert the BigDecimal type to javascript Number as shown below, then the output  shows the correct value.( Not sure if that's the right fix)

```code
if (type == 'BigDecimal') {
                    result[cmd.label] = Number(self._rs[getter](i));
                    return;
                  }
```
Please advise.

**Comment by CraZySacX** [comment]
You code example for converting is correct.  You must convert the returned Java types into a corresponding Javascript type.
