### ISSUE TITLE
node-jdbc automatically uninstalling

### ISSUE THREAD

**Issue by KalaiselvanMahendran** [CraZySacX/node-jdbc#157]
Hi,

After installing the node-jdbc module in my application, if I install new npm module JDBC module automatically getting removed from the node_modules folder.

How to solve this issue @CraZySacX

**Comment by CraZySacX** [comment]
Did you install it with npm i --save?   If it isn't persisted in your package.json, the auto-pruning may remove it.   It's that's not the case, I'm not sure why it would be disappearing.

**Comment by CraZySacX** [comment]
Closing.  Feel free to re-open if you think this is caused by node-jdbc.
