### ISSUE TITLE
jdbc async

### ISSUE THREAD

**Issue by royigoldi** [CraZySacX/node-jdbc#158]
Hi all,

I am calling to Claoudera Impala using the JDBC and retrive 30000 rows and 20 columns:
the execute take second and the toObjectArray take 25 seconds!!!

there is option to boost the performance?
I try to set to the statment the setFetch to 10 or 100 or 1000 or 10000 but nothing change...

Thanks a lot for your answers,
Royi

**Comment by CraZySacX** [comment]
I'm going to need some more information.   See if you can pin down exactly where in ```toObjectIter``` that the slow down is occurring.   There are a couple of calls to the Java API there, but nothing that should be that time consuming.

**Comment by CraZySacX** [comment]
Closing.   Feel free to re-open if you have more details.

**Comment by dbit-xia** [comment]
I encapsulated it in Java, so much more efficient

[MyJdbc](Https://github.com/dbit-xia/MyJdbc)
