### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by pnahtanoj** [CraZySacX/node-jdbc#161]
Working well on my dev machine (mac) with:

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

However, I'm getting seg faults with:

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

java -version
java version "1.7.0_151"
OpenJDK Runtime Environment (IcedTea 2.6.11) (7u151-2.6.11-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.151-b01, mixed mode)

node ./index.js
TRYING TO START: /opt/cb-customer-drivers/AthenaJDBC41-1.1.0.Prod.jar
Segmentation fault (core dumped)

Common settings:

node -v
v8.2.1

npm -v
5.5.1

Apologies if that's not enough information - I'm happy to provide more.

**Comment by CraZySacX** [comment]
Try upgrading the runtime on your ubuntu box/vm to Java 8.    The AthenaJDBC driver doesn't work with Java 7.

> Thank you very much for contacting us. Please note Athena JDBC driver works specifically with Java 8 only. There is no support for Java 7. 

See https://forums.aws.amazon.com/thread.jspa?threadID=247321
