### ISSUE TITLE
Unit testing errors

### ISSUE THREAD

**Issue by pnahtanoj** [CraZySacX/node-jdbc#162]
Since jdbc inclusion, my unit tests are failing with:

Assertion failed: (result->IsNull()), function ensureJvm, file ../src/java.cpp, line 119.

I've tried including:

const jinst = require('jdbc/lib/jinst');

if (!jinst.isJvmCreated()) {
  jinst.addOption('-Xrs');
  jinst.setupClasspath(['/Users/jprice/Desktop/AthenaJDBC41-1.1.0.Prod.jar']);
}

at the top of my tests (just a guess), but that doesn't seem to help.

**Comment by CraZySacX** [comment]
Not sure without the full context, but you also need to create a ```Pool``` instance before the jvm is created.   Take a look at the unit tests in this project for some examples.

```
setUp: function(callback) {
    testpool = new Pool(config);
    testpool.initialize(function(err) {
      callback();
    });
  },
  tearDown: function(callback) {
    testpool = null;
    callback();
},
```

**Comment by CraZySacX** [comment]
Closing.   Feel free to re-open if you are still having issues.
