### ISSUE TITLE
Is SQL Injection prevention built into this great package?

### ISSUE THREAD

**Issue by ngwwm** [CraZySacX/node-jdbc#166]
Is SQL Injection prevention built into this great package?

**Comment by juvation** [comment]
yes - as long as you use PreparedStatements with question marks for your values. ie, use the JDBC API as intended, and don't substitute values into SQL yourself.

**Comment by CraZySacX** [comment]
To expand on the previous comment, prevention is not built in directly to the library, however if used as described above you will be protected.
