### ISSUE TITLE
Java RuntimeException for failed queries

### ISSUE THREAD

**Issue by izikorgad** [CraZySacX/node-jdbc#174]
In some rare cases, when the query fails entirely, a run-time exception is thrown (and not handled):
'Reject row count exceeded.',
'\r',
'\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r',
'\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r',
'\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r',
'\tat java.lang.reflect.Method.invoke(Method.java:498)\r',
'',
' at Object.next (node_modules\jdbc\lib\resultset.js:103:38)',
' at node_modules\jdbc\lib\resultset.js:68:23',
' at node_modules\jdbc\lib\resultset.js:98:9',
' at node_modules\jdbc\lib\resultsetmetadata.js:12:14' ] }

Please see PR #173

**Comment by CraZySacX** [comment]
Merged.

**Comment by izikorgad** [comment]
Hi @CraZySacX,
When do you plane to reales a new version? 
This fix is critical for us.
Thanks.

**Comment by CraZySacX** [comment]
I will do it in a few hours.  12:00 Eastern time.

**Comment by CraZySacX** [comment]
Sorry, got pulled into getting a release prepared for my day job so I didn't get to this over lunch.   I haven't forgotten, but it'll have to be after my work day.  Sorry for the delay.

**Comment by CraZySacX** [comment]
Just pushed 0.6.2

**Comment by izikorgad** [comment]
Thanks for the quick response.
We really appreciate it!
