### ISSUE TITLE
Please update to newest node-java

### ISSUE THREAD

**Issue by briancray** [CraZySacX/node-jdbc#199]
Support for node 12 was added node-java 0.12.0

**Comment by jaubourg** [comment]
That would be awesome! But I'm wondering how active `node-jdbc` is. @CraZySacX, are you still maintaining this module?

**Comment by PrashantN86** [comment]
Is anyone maintaining this module? node-java update is critical for using this module on latest node version. Any help on this would be really appreciated 🥇

**Comment by technicallynick** [comment]
Bump for importance. This is preventing a much needed update in a production system for me. @CraZySacX are you still planning on maintaining this package?

**Comment by jaubourg** [comment]
For those in need of a quick "fix". If you're using `yarn` as your module manager, simply add:

```json
"resolutions": {
  "jdbc/java": "^0.12.0"
},
```

in the `package.json` file of the project depending on `node-jdbc`. This will override the version of `node-java` `node-jdbc` depends on.

It's hackish but it should get the work done.

**Comment by briancray** [comment]
Open PR #201 🤞

**Comment by CraZySacX** [comment]
Sorry I've been away from this for a long time.   I'll get this merge in shortly.  If someone is interested in taking ownership of this repository I'd be more than willing to hand it over.  I don't have much time at this point to maintain it like I should.

**Comment by CraZySacX** [comment]
Merged and published.
