### ISSUE TITLE
Wrong conversion for BigDecimal types

### ISSUE THREAD

**Issue by ishtartec** [CraZySacX/node-jdbc#213]
Hi!

https://github.com/CraZySacX/node-jdbc/blob/a9dd8efd96482d0f6ad788ce70ac18d0d9890b13/lib/resultset.js#L126

This line is breaking the behavior of queries. It is returning only the integer part, removing the decimals:
```if(type === 'BigDecimal') type = 'Int';```

I guess it should be changed to something like:
```if(type === 'BigDecimal') type = 'Double';```

I have tested this change and sets the expected and correct behavior.

**Comment by CraZySacX** [comment]
Fixed with the latest release (0.7.4).   Also added a test to ensure that decimals are preserved.
