### ISSUE TITLE
Add support for loading multiple jar files onto the classpath

### ISSUE THREAD

**Issue by CraZySacX** [CraZySacX/node-jdbc#25]
Some JDBC drivers are packaged in multiple JAR files or have dependencies in more than one jar file.  We need to add support for loading more than one JAR file onto the classpath.

**Comment by asnir** [comment]
Consider the use of the following [lib](https://www.npmjs.com/package/node_classpath_builder)
https://github.com/CraZySacX/node-jdbc/issues/18
