### ISSUE TITLE
pinned 0.9.2 java version not installing on Ubuntu 12.04 32bit

### ISSUE THREAD

**Issue by bigmonkeyboy** [CraZySacX/node-jdbc#31]
When I try to install on Ubuntu 12.04 32bit version I get an error when the pre-req java npm tries to recompile
     /usr/bin/ld: cannot find -ljvm ....
If I just npm install java it works fine as it's at level 0.9.4
Can you re-look to see if your problem at 0.9.3 on windows has been fixed so you can unpin or move the pin for the version of java npm ?

**Comment by CraZySacX** [comment]
Yep, will do.

**Comment by CraZySacX** [comment]
Try it now with version 0.0.12.  I've bumped the minimum version of node-java to 0.4.4.

**Comment by bigmonkeyboy** [comment]
Now works great for me - Thanks...
