### ISSUE TITLE
Fetch Size Configureable?

### ISSUE THREAD

**Issue by sagax85** [CraZySacX/node-jdbc#36]
Hi,

I am using the node-jdbc package to connect to a hive2 server and was wondering whether it is possible to set the fetch size? I have some queries that are fairly big (500MB+) and would thus like to receive it in chunks.

Many thanks!

**Comment by CraZySacX** [comment]
I took a quick look at how hive jdbc driver allows you to change the fetch size, and the current version of this package doesn't have this type of flexibility yet.   I can look at implementing a "fetch" function that allows more configuration of the statement and resultset fetching.

**Comment by sagax85** [comment]
thanks for the quick answer! 

As an example, the module node-hive (https://github.com/forward/node-hive) provides a "fetchInBatch" function where you can define the batchSize. Something like this would be great.

**Comment by isartmontane-socialbro** [comment]
What about result streaming support? Is that something easier to do?

**Comment by CraZySacX** [comment]
I'd like to get fetch implemented before 1.0.   I haven't looked into streaming, but I will.

**Comment by CraZySacX** [comment]
I don't have a good way to test this, but you can set fetchsize in config now and executeQuery will read it and call setFetchSize on the statement.
