### ISSUE TITLE
Question on usage

### ISSUE THREAD

**Issue by scratch28** [CraZySacX/node-jdbc#41]
I am trying to use this to connect with HiveServer2 (Cloudera Impala) 
I am following the config outlined here
https://cwiki.apache.org/confluence/display/Hive/HiveServer2+Clients#HiveServer2Clients-JDBCClientSampleCode
and converting as needed to js

var config = {
  libpath: '/home/ubuntu/downloads/impala_jdbc/hive-jdbc-0.13.1-cdh5.3.3.jar',
  libs:'/home/ubuntu/downloads/impala_jdbc/lib/*.jar',
  drivername: 'org.apache.hive.jdbc.HiveDriver',
  url: 'jdbc:hive2://localhost:21050/;auth=noSasl' + process.argv[2] 
};

but I am getting the following error 
 
/home/ubuntu/PlayArea/ImpalaJDBC/node_modules/jdbc/lib/jdbc.js:22
   java.classpath.push.apply(java.classpath, self._config.libs);
                       ^
TypeError: Function.prototype.apply: Arguments list has wrong type
    at JDBCConn.initialize (/home/ubuntu/PlayArea/ImpalaJDBC/node_modules/jdbc/lib/jdbc.js:22:24)
    at Object.<anonymous> (/home/ubuntu/PlayArea/ImpalaJDBC/server.js:12:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by Neablis** [comment]
I haven't succeeded at getting a impala jdbc driver to work yet so cant be a lot of help, but i can tell you 
libs:'/home/ubuntu/downloads/impala_jdbc/lib/*.jar'
needs to be
libs:['/home/ubuntu/downloads/impala_jdbc/lib/*.jar']

Otherwise you are trying to apply a array function to a string and get the error you specified.

**Comment by CraZySacX** [comment]
Closing this for now.  Let me know if I need to reopen after the syntax was fixed.
