### ISSUE TITLE
Not support SQL Server2014

### ISSUE THREAD

**Issue by aidtent** [CraZySacX/node-jdbc#45]
it's not work when connect with SQL Server 2014
var config = {
  libpath: './sqljdbc4.jar',
  drivername: 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
  url: 'jdbc:sqlserver://locahost;databaseName=test;',
  user: 'sa',
  password: 'sa',
};

there‘s no any Response and Error message

**Comment by CraZySacX** [comment]
I'll need more information about what you are experiencing in order to help out here.  I don't have access to SQL Server currently.  Maybe there is a dev version now that I can grab.

**Comment by CraZySacX** [comment]
Closing.  Try it again with the new api.
