### ISSUE TITLE
Redshift data access from node jdbc

### ISSUE THREAD

**Issue by Nagasai-Aytha** [CraZySacX/node-jdbc#46]
Hi ,

I am getting below error when i try to data from redshift with the below mentioned code

Code:

var jdbc = new ( require('jdbc') );

 var config = {

  libpath: 'C:/Users/ABCD/Desktop/jar/RedshiftJDBC41-1.1.6.1006.jar',

  //libs: [__dirname + 'path/to/other/jars.jar'],

  drivername: 'com.amazon.redshift.jdbc41.Driver',

  url: 'jdbc:redshift://examplecluster.abc123xyz789.us-west-2.redshift.amazonaws.com:5439/dev',

  user: 'xxxx',

  password: 'xxxxx'

};

 

jdbc.initialize(config, function(err, res) {

  if (err) {

    console.log(err);

  }

});

var genericQueryHandler = function(err, results) {

  if (err) {

    console.log(err);

  } else if (results) {

    console.log(results);

  }

  
  jdbc.close(function(err) {

    if(err) {

      console.log(err);

    } else {

      console.log("Connection closed successfully!");

    }

  });

 

};

jdbc.open(function(err, conn) {

  if (conn) {

    				// SELECT statements are called with executeQuery 

    				jdbc.executeQuery("select * from information_schema.tables", genericQueryHandler);

   }

});

Error:

C:\Users\ABCD> node redshift.js
C:\Users\ABCD\node_modules\jdbc\lib\jdbc.js:62

    if(this._props.getPropertySync('user') === undefined){

                   ^

TypeError: undefined is not a function

    at JDBCConn.initialize (C:\Users\ABCD\node_modules\jdbc\lib\jdbc.js:62:20)

    at Object.<anonymous> (C:\Users\ABCD\Desktop\AngularJS\redshift.js:15:6)

    at Module._compile (module.js:460:26)

    at Object.Module._extensions..js (module.js:478:10)

    at Module.load (module.js:355:32)

    at Function.Module._load (module.js:310:12)

    at Function.Module.runMain (module.js:501:10)

    at startup (node.js:129:16)

    at node.js:814:3

Could you please let me know whether there is nay issue with the above mentioned node jdbc usage for redshift?

Thanks

**Comment by Nagasai-Aytha** [comment]
To solve the above problem.

Please replace the below code 

  user: 'xxxx',
  password: 'xxxxx'

Replace with below properties code

properties:[
    
    ['user', 'xxxxxx'],

    ['password', 'xxxxxx']
            
           ]



Thanks
Sai

**Comment by LukeWoodward** [comment]
To clarify, this came up on StackOverflow recently: http://stackoverflow.com/questions/32001900

I can only conclude that the problems were introduced by merging cmaurer's pull request #44.  It has the side-effect of breaking support for the `user` and `password` configuration properties.

Your test file `test-hsqldb.js` has a `configWithUserInConfig` object that has the username and password specified in the `user` and `password` configuration properties.  However, there aren't any tests that use this configuration, so you got no test failures after merging cmaurer's pull request.  Perhaps if you'd had any such tests, you would have noticed the problem.

It's unsatisfactory to have example code on the front page of your repository to say "here's how to use XYZ" when it doesn't work.

Finally, please document the format of the `properties` element of the configuration.  It would seem intuitive that you would use something like

    properties: {
        user: 'xxxx',
        password: 'xxxxx'
    }

but this does not work.  Instead, it should be 

    properties: [
        ['user', 'xxxx'],
        ['password', 'xxxxx']
    ]

**Comment by CraZySacX** [comment]
Closing.  Updated README.md to reflect new configuration options.
