### ISSUE TITLE
Specify driver name?

### ISSUE THREAD

**Issue by tristanz** [CraZySacX/node-jdbc#51]
In the old API it used to be possible to specify a driver name.  Is this still possible?  I've been digging around but haven't seen the option.

**Comment by CraZySacX** [comment]
As of Java 1.6 you don't need to specify the driver (see [here](http://docs.oracle.com/javase/6/docs/api/java/sql/DriverManager.html)).  It will do it's best to find the appropriate driver on the classpath for you.   If there is a specific need for specifying a driver name for some reason, I'd be happy to add it back in.

**Comment by CraZySacX** [comment]
I'm closing this for now.  Feel free to reopen if you need the driver name to be configurable.
