### ISSUE TITLE
timing out or canceling initialize

### ISSUE THREAD

**Issue by vahaknp** [CraZySacX/node-jdbc#55]
I was wondering whether there is a way to time-out or cancel the `.initialize` function.

```
var jdbc = new JDBC(config);

jdbc.initialize(function(err) {
  if (err) {
    console.log(err);
  } else {
    console.log("Connected.");
  }
});
```

Currently, I'm trying to connect to Impala. When Impala is responsive, it works fine, but occasionally when it is overloaded, it just lags and does not resolve or return an error.

**Comment by vahaknp** [comment]
Also, should https://github.com/CraZySacX/node-jdbc/blob/master/lib/pool.js#L74 be `callback(err)`?

**Comment by CraZySacX** [comment]
There are a couple things to try

1.  See if your connection properties include a timeout property.  If they do, set that to something appropriate in the properties object on the config object.
2.  Creative use of the setTimeout function.
3.  I could add support to the pool for specifying the login timeout time, that is a field in the DriverManager class.

As for your followup question, the line you are referring to is correct.  That is the successful path, and null is appropriate for the err value in that case.

However it wasn't checking for an error.  I'll fix that.  Should be:

```javascript
if (err) {
  return callback(err);
} else {
  _.each(conns, function(conn) {
    self._pool.push(conn);
  });
  return callback(null);
}
```

**Comment by vahaknp** [comment]
I discovered this property: 
```
properties: [['socketTimeout', '10000']]
```
in page 12 of the JDBC manual: https://github.com/ripple/monitoring-tools-backend/blob/master/lib/Cloudera%20-%20Simba%20JDBC%20Driver%20for%20Cloudera%20Impala%20Install%20Guide.pdf

This works most of the time, but when I'm making a health check call (just opening and closing a connection), eventually the ```jdbc.open(function(err, conn) {});``` function is lagging, not returning anything, and not timing out.

Any idea why the `.open` function would hang instead of responding with _something_?

**Comment by vahaknp** [comment]
I think it turns out that the `.close` function isn't actually killing the connections. I'm still having trouble figuring out why.
