### ISSUE TITLE
toObjArray number out of range

### ISSUE THREAD

**Issue by coretechs** [CraZySacX/node-jdbc#63]
I'm working with an H2 DB that is using signed BIGINT(19) values that are being manually converted after parsing results.  Since the API refactor, using toObjArray is converting internally using Int causing out of range error:

>/node_modules/jdbc/lib/resultset.js:100
>                result[cmd.label] = self._rs['get' + type + 'Sync'](i);
>Error: Error running instance method
>org.h2.jdbc.JdbcSQLException: Numeric value out of range: "47475721164246888" [22003-176]

I was able to work around the error by changing to the String type for BIGINT in ResultSet():
`typeNames[java.getStaticFieldValue("java.sql.Types", "BIGINT")] = "String";`

Also did this to support VARBINARY:
`typeNames[java.getStaticFieldValue("java.sql.Types", "VARBINARY")] = "String";`

**Comment by CraZySacX** [comment]
BIGINT and VARBINARY should be supported correctly now with the latest merges.  Feel free to re-open if you are still experiencing issues.

**Comment by coretechs** [comment]
The default mapping to String solves the missing VARBINARY type, but BIGINT is still not working correctly.

Long is the correct type for mapping to Java but JavaScript numeric max is a 32-bit int, so with the latest change it is now truncating the result.  See the java node module README.md section on java.lang.Long.

For BIGINT I recommend using String as the default type in rs objects as that is what will work in JavaScript without truncation.

**Comment by CraZySacX** [comment]
This has been fixed in the latest release.   I've also added a test so this doesn't regress.
