### ISSUE TITLE
Response limit exceed

### ISSUE THREAD

**Issue by oshribin** [CraZySacX/node-jdbc#69]
Teradata limit the maximum open response to 16 ( see link below ), every 16 queries with the same connection will cause a fatal error, to avoid this error, responses need to be closed once you get all the result,
 maybe you need to expose the result-set return from the db so it will be easy to handle it.
currently i am accessing the _rs object  from the resultSet returned by executeQuery.
but its not part of the api

http://developer.teradata.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_5.html#CHDGCHBB

**Comment by CraZySacX** [comment]
Interesting.  Good catch.  I'll add close to the api for the various statements and result set.

**Comment by CraZySacX** [comment]
Should be fixed with 8abed69522a832911e04d075397a68abc779cc97.  Closing.
