### ISSUE TITLE
What happened to the drivername config option ?

### ISSUE THREAD

**Issue by rawc0der** [CraZySacX/node-jdbc#70]
I'm using Apache Drill with the jdbc connection. Until the new updates, I got it working fine.
In the previous versions (0.0.12) the config object had drivername as a required field. Since I've updated and refactored the code conforming to the new api, I'm getting this error from the jvm:

``` java.sql.SQLException: No suitable driver found for jdbc:drill:zk=127.0.0.1:2181/drill/drillbits1 ```

My code looks like this:
```
config = 
  url: 'jdbc:drill:zk=127.0.0.1:2181/drill/drillbits1'
  drivername: 'org.apache.drill.jdbc.Driver'
  minpoolsize: 10
  maxpoolsize: 100
  properties: {}

...
if not jinst.isJvmCreated()
  jarPath = path.resolve __dirname + '/../../server/private/drill-jdbc-all-1.1.0.jar'
  jinst.addOption("-Xrs")
  jinst.setupClasspath([
    jarPath
  ])
...
@_drillJdbc = new JDBC(config)
```
How can I pass the drivername option in the latest version?

**Comment by CraZySacX** [comment]
The (DriverManager)[http://docs.oracle.com/javase/6/docs/api/java/sql/DriverManager.html] class as of Java 6 tries to load to proper driver automatically.   I removed the Class.forName call that supplying the drivername property enabled.   However, some of the older drivers cannot be loaded automatically.  You can check for the following file in your driver: META-INF/services/java.sql.Driver.  If it's not there you driver is old (or non-conforming).   Either way, I plan to add back in support for loading the driver by Class.forName if a drivername property is supplied.

In the meantime, you can add:
```javascript
var driver = java.newInstanceSync("org.apache.drill.jdbc.Driver");
```

**Comment by CraZySacX** [comment]
I've pushed out the drivername support to master.

**Comment by CraZySacX** [comment]
Closing with latest release.
