### ISSUE TITLE
npm install exit code 1 node-gyp rebuild

### ISSUE THREAD

**Issue by ganna-shmatova** [CraZySacX/node-jdbc#72]
tried with `npm install jdbc`

tried with `npm install jdbc --msvs_version=2012`:
![image](https://cloud.githubusercontent.com/assets/7226694/11005756/b7dbd2d2-848d-11e5-8e1e-37a7dd0fe557.png)

opened same ticket in `java` module: https://github.com/joeferner/node-java/issues/274

**Comment by CraZySacX** [comment]
Here is my output on a fresh install of node, one thing to try is installing node-gyp as global.

```
C:\projects\node-jdbc>npm cache clear

C:\projects\node-jdbc>npm install
\
> java@0.6.0 install C:\projects\node-jdbc\node_modules\java
> node-gyp rebuild


C:\projects\node-jdbc\node_modules\java>if not defined npm_config_node_gyp (node "C:\software\node\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gy
p\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  java.cpp
  javaObject.cpp
  javaScope.cpp
  methodCallBaton.cpp
  nodeJavaBridge.cpp
..\src\java.cpp(455): warning C4311: 'type cast': pointer truncation from 'DynamicProxyData *' to 'long' [C:\projects\node-jdbc\node_modules\java\build\nodejav
abridge_bindings.vcxproj]
..\src\java.cpp(455): warning C4302: 'type cast': truncation from 'DynamicProxyData *' to 'long' [C:\projects\node-jdbc\node_modules\java\build\nodejavabridge_
bindings.vcxproj]
  utils.cpp
  win_delay_load_hook.c
     Creating library C:\projects\node-jdbc\node_modules\java\build\Release\nodejavabridge_bindings.lib and object C:\projects\node-jdbc\node_modules\java\buil
  d\Release\nodejavabridge_bindings.exp
  Generating code
  Finished generating code
  nodejavabridge_bindings.vcxproj -> C:\projects\node-jdbc\node_modules\java\build\Release\\nodejavabridge_bindings.node

> java@0.6.0 postinstall C:\projects\node-jdbc\node_modules\java
> node postInstall.js

java@0.6.0 node_modules\java
├── async@0.9.0
├── nan@2.0.9
├── lodash@3.7.0
├── find-java-home@0.1.2 (which@1.0.9)
└── glob@5.0.5 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.10)
```

**Comment by ganna-shmatova** [comment]
deleted app data npm and npm-cache folders from all users

uninstalled node.js
reinstalled node.js 4.2.2

npm install node-gyp -g
successfully

same thing, sadly...
`npm install jdbc`:
![image](https://cloud.githubusercontent.com/assets/7226694/11046641/901c1470-86fc-11e5-87fa-1307da4743b7.png)
`npm install jdbc --msvs_version=2012`:
![image](https://cloud.githubusercontent.com/assets/7226694/11046664/a94aed68-86fc-11e5-8ee1-12865f70b10b.png)

**Comment by CraZySacX** [comment]
Yeah you may have to follow up on the node-java issue.  You are getting some compilation errors in the node-java module I have never seen before.  I'm not sure what versions of msvc are supported.

**Comment by CraZySacX** [comment]
Closing.  This is upstream.  Feel free to reopen if you are still having issues.
