### ISSUE TITLE
404 on NPM download?

### ISSUE THREAD

**Issue by natdm** [CraZySacX/node-jdbc#73]
https://registry.npmjs.org/node-jdbc renders 404.

**Comment by CraZySacX** [comment]
https://registry.npmjs.org/jdbc is the correct url.    Do I have it listed incorrectly somewhere?

**Comment by natdm** [comment]
npm install sends you to the link I pasted.

On Mon, Nov 16, 2015 at 9:03 AM, Jason Ozias <notifications@github.com>
wrote:

> https://registry.npmjs.org/jdbc is the correct url. Do I have it listed
> incorrectly somewhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CraZySacX/node-jdbc/issues/73#issuecomment-157080366>.
>



-- 
___________________________
Nathan Hyland
(602)740-5705

**Comment by CraZySacX** [comment]
Ah, I have the install command wrong in the README.

```npm install jdbc```  is the correct command.

**Comment by natdm** [comment]
Correction - your documentation says node-jdbc.

On Mon, Nov 16, 2015 at 9:08 AM, Nathan Hyland <nathan.hyland@gmail.com>
wrote:

> npm install sends you to the link I pasted.
>
> On Mon, Nov 16, 2015 at 9:03 AM, Jason Ozias <notifications@github.com>
> wrote:
>
>> https://registry.npmjs.org/jdbc is the correct url. Do I have it listed
>> incorrectly somewhere?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CraZySacX/node-jdbc/issues/73#issuecomment-157080366>
>> .
>>
>
>
>
> --
> ___________________________
> Nathan Hyland
> (602)740-5705
>



-- 
___________________________
Nathan Hyland
(602)740-5705
