### ISSUE TITLE
Un-promisifiable / callback argument consistency issue

### ISSUE THREAD

**Issue by dash-** [CraZySacX/node-jdbc#80]
Let me begin by saying that this library is a lifesaver.  I thought I was hosed when my boss told me we needed to connect to a Derby database from Node.js.  I wasn't even sure it was possible until I found this package.  Unfortunately, I have a core issue with the implementation.

1. There are numerous classes with methods that do not maintain a consistent method interface in regards to callback arguments (ie, sometimes callback is the last argument, sometimes it's the first argument, and sometimes it's number two).

2. Further, it is the convention in JS to accept the callback as the last parameter, and this convention is not adhered to.

3. Further, because this convention is not adhered to, these objects are not completely promisifiable.  That is, the promisifyAll method provided by promise libraries do not correctly promisify all the methods of these classes, particularly when all arguments are passed to the methods.

4. Finally, callback should still be the last argument even if some arguments are optional in order to keep in accordance with (2) and (3) above.

Examples:

Connection.createStatement
Connection.getClientInfo
Connection.prepareCall
Connection.prepareStatement
Connection.rollback
Connection.setClientInfo
Connection.setSavepoint
CallableStatement.getDate
CallableStatement.getObject
DriverManager.getConnection
Statement.executeUpdate

This may be an exhaustive list, I'm not completely sure.

I also recognize that changing the interface agreement for these methods would be a breaking change.  I'm considering creating a promisifiable version as an independent package.

**Comment by CraZySacX** [comment]
Yeah it was definitely not implemented originally with an eye toward promise.  I be happy to take a pull request and update the semver if you would like to implement it.   We've already gone through one major API change, so it's not unwarranted.   I'd like to get it settled before 1.0 however.

**Comment by dash-** [comment]
That's great news.  I'll work on it today, and hopefully have a pull request ready today or tomorrow.

**Comment by dash-** [comment]
I noticed Statement.executeUpdate takes an argument it never uses - and because indentation is messed up in that function, I assume it was gutted from a previous version.

Can we just remove arg1 completely?  Or should it stay there for later purposes?

**Comment by dash-** [comment]
For now, I'm leaving it there and doing a 1-to-1 translation.  You can remove it later if desired.

**Comment by dash-** [comment]
Also, I don't have the necessary resources to test this at the moment.  I could install the necessary databases to run the tests, but my resources are limited (I'm running a tiny virtual machine and don't have access to outside resources).  Would it be possible for me to submit the pull request and have you test it prior to pushing it to master?

Otherwise, I'm done coding necessary changes.

**Comment by CraZySacX** [comment]
Yeah that's fine.  I'll get it tested.

**Comment by dash-** [comment]
Okay, sweet.  I found a couple more things to do before I put in the pull request though.

**Comment by CraZySacX** [comment]
Merged to master, and tests updated to work.   I'm going to review the rest of the functions before I bump and release 0.2, but you should be able to use the from master for now.

**Comment by dash-** [comment]
Sounds great.  Thanks man.
