### ISSUE TITLE
Is it possible to gc JDBC instance or change JDBC config after creation?

### ISSUE THREAD

**Issue by ganna-shmatova** [CraZySacX/node-jdbc#88]
The readme does not specify.

In my case, JDBC is configurable. So it is possible that a server may change host or user/pw over the life of the application.

**Comment by CraZySacX** [comment]
You should be able to set the pool and the config to null, and then reassign them, but I haven't tested this.   This should allow the javascript object to be garbage collected, but I'm not positive what will happen in the jvm.

**Comment by CraZySacX** [comment]
Closing.  This is possible by nulling and reassigning.
