### ISSUE TITLE
DatabaseMetaData object is virtually bare, missing a lot of functionality

### ISSUE THREAD

**Issue by dash-** [CraZySacX/node-jdbc#90]
DatabaseMetaData only has two methods currently:

getSchemas
getTables

The original DatabaseMetaData has significantly more, as demonstrated at:
https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html

**Comment by dash-** [comment]
Posted pull request #91 - Includes over 3000 lines of code, although it's admittedly mostly just ported method signatures and documentation containing fairly minimal boilerplate.  That having been said, all methods do basic parameter type checking, and returned objects are wrapped appropriately where it was practical for this release.  The only exception to returning wrapped objects is databasemetadata.getRowIdLifetime which returns a java.sql.RowIdLifetime for which we don't already have a wrapper class.

https://docs.oracle.com/javase/7/docs/api/java/sql/RowIdLifetime.html

Such a wrapper class probably should be built if we want to return a wrapped object.  It's not terribly complex (far less complex than the java.sql.DatabaseMetaData class), but I just don't have time for that work at the moment considering I don't need it right now.

**Comment by CraZySacX** [comment]
Merged.  Closing.
