### ISSUE TITLE
ResultSet - Null integer columns returned as a zero

### ISSUE THREAD

**Issue by dash-** [CraZySacX/node-jdbc#94]
The implementation of ResultSet.toObjArray, ResultSet.toObject, and ResultSet.toObjectIter (the former two depending upon the latter), simply calls java.sql.ResultSet.getInt() [as _rs.getIntSync] for Integer values.  Unfortunately, when databases have null values for integer columns, java.sql.ResultSet.getInt() returns 0.  Which is definitely not the same as null, and the two cannot somehow later be separated.  Zero and null are both separate necessary values.

This problem is solved in the Java world by calling java.sql.ResultSet.getObject() - and if the result is Null, it's null.  Otherwise, you can either cast to Integer or call getInt() for the int value.

See: http://stackoverflow.com/questions/5881834/getting-integer-object-from-resultset

**Comment by CraZySacX** [comment]
Merged.  Closing.

**Comment by dash-** [comment]
I'd like to request a npm publish fairly soon.  I'm about to release
node-waterline-derby, a waterline adapter for Derby, and it depends on the
newest changes in node-jdbc.

:-)

**Comment by CraZySacX** [comment]
Sure.  Bumping to 0.2.0 due to API changes.

**Comment by dash-** [comment]
Thanks!

**Comment by CraZySacX** [comment]
Done

**Comment by EmilCernega** [comment]
Hello,
This issue appears again after commit 10a1928d8c65cd59ea193787d5cbe93e812278f9
this was changed:
```
               - if(type === 'BigDecimal') type = 'Int';
               + if (type === 'BigDecimal') type = 'Double';
```
But the if condition didn't change:
```
 if (type === 'Int' && _.isNull(self._rs.getObjectSync(cmd.label))) {
                    result[cmd.label] = null;
                    return;
                  }
```
Thank you,
Emil
