### ISSUE TITLE
Reserve-Release function don't close the connection

### ISSUE THREAD

**Issue by romandoma** [CraZySacX/node-jdbc#96]
Hi, great library!

In java for release a conecction i put this code:
```
rs.close();
stmt.close();
con.close();
```

I tried the next code but the conecction still alive after '**release**' function, until the run finish:
```
..
...
var hsqldb2 = new JDBC(config);
hsqldb2.reserve(function(err, connObj) {
if (connObj) {
        console.log("Using connection: " + connObj.uuid);
    }else{
        console.log("error on reserve");
    }`
    hsqldb2.release(connObj , function(err) {
    if (err) {
      console.log(err.message);
    } 
    sleep(20000);
  });
});
function sleep(miliseconds) {
   var currentTime = new Date().getTime();
   console.log("sleeping: " + miliseconds)

   while (currentTime + miliseconds >= new Date().getTime()) {
   }
}
```
Wich are the functions I have to use for close the conecction in the right way?

Thanks a lot..

**Comment by CraZySacX** [comment]
The reserve functions grabs a connection from the connection pool.   The release function returns it back into the pool (without closing it).   This is done to conserve resources.   If you actually want to close all of the pooled connections when you are done using the pool you could add a closeAll or something similar to pool.js, and loop through all the connections and call con.close() explicitly on them.

**Comment by CraZySacX** [comment]
PR #98 resolves this.  Closing.
