### ISSUE TITLE
Not able to Reserve the connection to Impala

### ISSUE THREAD

**Issue by sunil-vtm** [CraZySacX/node-jdbc#99]
Hi,
When reserving the connection to Impala, stucks at the point where it gets connection in pool.js.
The behaviour is only after couple of requests done successfully(first two requests are good, I am able to fetch the results. from the 3rd request it stucks when reserve the connection).here is the method where pointer stucks, it's not coming to the error block also:

> var addConnection = function(url, props, callback) {
> dm.getConnection(url, props, function(err, conn) {
>     if (err) {
>       return callback(err);
>     } else {
>       return callback(null, {uuid: uuid.v4(), conn: new Connection(conn)});
>     }
>   });
> };
> I attached code here, please check it, is anything to be handled properly.
> [jdbccode.txt](https://github.com/CraZySacX/node-jdbc/files/171896/jdbccode.txt)

Thanks & Regards,
Sunilkumar.V

**Comment by CraZySacX** [comment]
Closing due to age.  Feel free to re-open if this is still an issue.
